# Generated by Django 5.0.6 on 2024-06-27 15:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdministradorTallern',
            new_name='AdministradorTaller',
        ),
    ]
