# Generated by Django 5.0.6 on 2024-06-28 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_administradortallern_administradortaller'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='observaciones',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mecanico',
            name='especialidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.especialidad'),
        ),
    ]
