# Generated by Django 5.0.6 on 2025-06-19 02:49

from django.db import migrations

# Import Group model directly for data migrations if apps.get_model is not strictly needed,
# but for consistency with schema changes and historical model states, apps.get_model is safer.
# from django.contrib.auth.models import Group

GROUP_NAMES = ['cliente', 'trabajador', 'administrador_ferreteria']

def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    for group_name in GROUP_NAMES:
        Group.objects.get_or_create(name=group_name)

def remove_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    # Only delete the groups we are certain this migration created.
    Group.objects.filter(name__in=GROUP_NAMES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        # It's good practice to add a dependency on the auth app's migrations
        # if you are manipulating auth models like Group, especially if there's
        # a chance this migration runs before auth tables are fully created.
        # However, '0001_initial' of 'core' might already make this implicit
        # if User/Group are foreign keys. For explicit safety:
        ('auth', '__latest__'), # Ensures auth tables are up-to-date
    ]

    operations = [
        migrations.RunPython(create_groups, remove_groups),
    ]
