# Generated by Django 5.0.6 on 2024-06-28 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_trabajo_descripcion_alter_trabajo_diagnostico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
