# Generated by Django 5.0.6 on 2024-06-28 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_trabajo_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='fecha_actualizacion',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
