# Generated by Django 5.0.6 on 2024-06-28 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_trabajo_fecha_actualizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
